Repository bottlerocket-os/bottlerocket-update-operator, pull requests merged in 2022-01, with the labels that each got.

#140 Consolidate Kubernetes Resources into a Single File
  bottlerocket-update-operator.yaml
  yamlgen/build.rs
  yamlgen/deploy/bottlerocket-node-crd.yaml
  yamlgen/deploy/bottlerocket-update-operator.yaml
Labels: 0.2.0-dev

#137 Add drain support to the apiserver
  Cargo.lock
  agent/Cargo.toml
  agent/src/agentclient.rs
  apiserver/Cargo.toml
  apiserver/src/api/drain.rs
  apiserver/src/api/mod.rs
  apiserver/src/client/error.rs
  apiserver/src/client/mock.rs
  apiserver/src/client/webclient.rs
  apiserver/src/constants.rs
  apiserver/src/error.rs
  apiserver/src/lib.rs
  controller/Cargo.toml
  models/Cargo.toml
  models/src/apiserver.rs
  models/src/node/client.rs
  models/src/node/drain.rs
  models/src/node/error.rs
  models/src/node/mod.rs
  yamlgen/Cargo.toml
  yamlgen/deploy/bottlerocket-update-operator.yaml
Labels: component/apiserver, component/agent, 0.2.0-dev

#141 0.2.0-integ test: Using single resource file.
  integ/src/updater.rs
Labels: 0.2.0-dev

#144 Remove unneeded permissions granted to agent
  models/src/agent.rs
  yamlgen/deploy/bottlerocket-update-operator.yaml
Labels: component/agent, 0.2.0-dev

#142 Fix bug preventing concurrent evictions
  models/src/node/drain.rs
Labels: component/apiserver, 0.2.0-dev

#145 Update bottlerocket SDK to v0.25.1
  Makefile
Labels: 0.2.0-dev

#138 0.2.0 agent: Restart the event loop when Errors are not fatal.
  agent/src/agentclient.rs
Labels: component/agent, 0.2.0-dev
